url: "https://RedeemerCityChurch.org"


collections:
  sermons:
  leaders:


## Podcast RSS configuration
podcast_subtitle: "Sermons from Redeemer City Church: Madison, WI" 
podcast_url: "https://RedeemerCityChurch.org"
podcast_album_art: "http://RedeemerCityChurch.org/assets/img/rccpodcastlogo.png"
podcast_title: Redeemer City Church Sermons
podcast_owner: Redeemer City Church
podcast_email: info@redeemercitychurch.org
podcast_category: Religion &amp; Spirituality
podcast_subcategory: Christianity
podcast_explicit: "no"
podcast_author: Redeemer City Church
podcast_description: "Sermons from Redeemer City Church: Madison, WI"
podcast_summary: "Sermons from Redeemer City Church: Madison, WI"
